# Site settings
title: Guok Blog    # 首页标题
SEOTitle: 锅ke的博客 | Guok Blog  # 浏览器标签栏的文字
header-img: img/home-bg.jpg    # 首页头部底图
email: guoke24s@gmail.com
description: "Software Engineer" # 自我简介，目前没显示
keyword: "Guok Blog, 博客, 个人网站, 互联网, Web, Android" # 关键词，目前没显示
#url: "https://guoke24.github.io" 
url: "https://guoke24.top"              # your host, for absolute URL
baseurl: ""                             # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     guoke24pro
#zhihu_username:     huxpro
github_username:    guoke24
#twitter_username:   huxpro
#facebook_username:  huxpro
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10    # 一页最多放几篇文章
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings，先到 Disqus 申请账号，并配置 Add Dusqus To Site，得到一个 webSite 的 shortname，填写到此处
disqus_username: guoke24

# Netease settings 网易跟帖，已经失效
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # 侧边栏开关
sidebar-about-description: "Step by step<br>不积跬步" # 侧边栏自我描述
sidebar-avatar: /img/avatar-guok-ny.jpg      # 侧边栏大头贴



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    #{
    #     title: "Su",
    #     href: "http://su.gallery/"
    # },
    {
       title: "Hux Blog",
       href: "https://huangxuan.me/"
    }
]
